function DefineTiles() {
_nullSpr = _sprites['null'];

	_TileTypes.stoneWall = new _SmartTileType( 'Stone Wall', false, false, true, _Selectors.OnlyWalls, {
		n:_sprites['stoneWall_n'],
		e:_sprites['stoneWall_e'],
		s:_sprites['stoneWall_s'],
		w:_sprites['stoneWall_w'],
		ne:_sprites['stoneWall_ne'],
		nw:_sprites['stoneWall_nw'],
		ns:_sprites['stoneWall_ns'],
		ew:_sprites['stoneWall_ew'],
		es:_sprites['stoneWall_es'],
		ws:_sprites['stoneWall_ws'],
		new:_sprites['stoneWall_new'],
		nes:_sprites['stoneWall_nes'],
		nws:_sprites['stoneWall_nws'],
		ews:_sprites['stoneWall_ews'],
		news:_sprites['stoneWall_news'],
		z:_sprites['stoneWall_z'],

		m_n:_sprites['stoneWall_n_know'],
		m_e:_sprites['stoneWall_e_know'],
		m_s:_sprites['stoneWall_s_know'],
		m_w:_sprites['stoneWall_w_know'],
		m_ne:_sprites['stoneWall_ne_know'],
		m_nw:_sprites['stoneWall_nw_know'],
		m_ns:_sprites['stoneWall_ns_know'],
		m_ew:_sprites['stoneWall_ew_know'],
		m_es:_sprites['stoneWall_es_know'],
		m_ws:_sprites['stoneWall_ws_know'],
		m_new:_sprites['stoneWall_new_know'],
		m_nes:_sprites['stoneWall_nes_know'],
		m_nws:_sprites['stoneWall_nws_know'],
		m_ews:_sprites['stoneWall_ews_know'],
		m_news:_sprites['stoneWall_news_know'],
		m_z:_sprites['stoneWall_z_know']
	} );

	_TileTypes.rockWall = new _SmartTileType( 'Rock Wall', false, false, true, _Selectors.OnlyWalls, {
		n:_sprites['rockWall_n'],
		e:_sprites['rockWall_e'],
		s:_sprites['rockWall_s'],
		w:_sprites['rockWall_w'],
		ne:_sprites['rockWall_ne'],
		nw:_sprites['rockWall_nw'],
		ns:_sprites['rockWall_ns'],
		ew:_sprites['rockWall_ew'],
		es:_sprites['rockWall_es'],
		ws:_sprites['rockWall_ws'],
		new:_sprites['rockWall_new'],
		nes:_sprites['rockWall_nes'],
		nws:_sprites['rockWall_nws'],
		ews:_sprites['rockWall_ews'],
		news:_sprites['rockWall_news'],
		z:_sprites['rockWall_z'],

		m_n:_sprites['rockWall_n_know'],
		m_e:_sprites['rockWall_e_know'],
		m_s:_sprites['rockWall_s_know'],
		m_w:_sprites['rockWall_w_know'],
		m_ne:_sprites['rockWall_ne_know'],
		m_nw:_sprites['rockWall_nw_know'],
		m_ns:_sprites['rockWall_ns_know'],
		m_ew:_sprites['rockWall_ew_know'],
		m_es:_sprites['rockWall_es_know'],
		m_ws:_sprites['rockWall_ws_know'],
		m_new:_sprites['rockWall_new_know'],
		m_nes:_sprites['rockWall_nes_know'],
		m_nws:_sprites['rockWall_nws_know'],
		m_ews:_sprites['rockWall_ews_know'],
		m_news:_sprites['rockWall_news_know'],
		m_z:_sprites['rockWall_z_know']
	} );

	_TileTypes.stoneFloor = new _SmartTileType( 'Stone Floor', true, true, false, _Selectors.Exclusive, {
		n:_sprites['stoneFloor_n'],
		e:_sprites['stoneFloor_e'],
		s:_sprites['stoneFloor_s'],
		w:_sprites['stoneFloor_w'],
		ne:_sprites['stoneFloor_ne'],
		nw:_sprites['stoneFloor_nw'],
		ns:_sprites['stoneFloor_ns'],
		ew:_sprites['stoneFloor_ew'],
		es:_sprites['stoneFloor_es'],
		ws:_sprites['stoneFloor_ws'],
		new:_sprites['stoneFloor_new'],
		nes:_sprites['stoneFloor_nes'],
		nws:_sprites['stoneFloor_nws'],
		ews:_sprites['stoneFloor_ews'],
		news:_sprites['stoneFloor_news'],
		z:_sprites['stoneFloor_z'],

		m_n:_sprites['stoneFloor_n_know'],
		m_e:_sprites['stoneFloor_e_know'],
		m_s:_sprites['stoneFloor_s_know'],
		m_w:_sprites['stoneFloor_w_know'],
		m_ne:_sprites['stoneFloor_ne_know'],
		m_nw:_sprites['stoneFloor_nw_know'],
		m_ns:_sprites['stoneFloor_ns_know'],
		m_ew:_sprites['stoneFloor_ew_know'],
		m_es:_sprites['stoneFloor_es_know'],
		m_ws:_sprites['stoneFloor_ws_know'],
		m_new:_sprites['stoneFloor_new_know'],
		m_nes:_sprites['stoneFloor_nes_know'],
		m_nws:_sprites['stoneFloor_nws_know'],
		m_ews:_sprites['stoneFloor_ews_know'],
		m_news:_sprites['stoneFloor_news_know'],
		m_z:_sprites['stoneFloor_z_know'],
	} );

	_TileTypes.dirtFloor = new _SmartTileType( 'Dirt Floor', true, true, false, _Selectors.Exclusive, {
		n:_sprites['dirtFloor_n'],
		e:_sprites['dirtFloor_e'],
		s:_sprites['dirtFloor_s'],
		w:_sprites['dirtFloor_w'],
		ne:_sprites['dirtFloor_ne'],
		nw:_sprites['dirtFloor_nw'],
		ns:_sprites['dirtFloor_ns'],
		ew:_sprites['dirtFloor_ew'],
		es:_sprites['dirtFloor_es'],
		ws:_sprites['dirtFloor_ws'],
		new:_sprites['dirtFloor_new'],
		nes:_sprites['dirtFloor_nes'],
		nws:_sprites['dirtFloor_nws'],
		ews:_sprites['dirtFloor_ews'],
		news:_sprites['dirtFloor_news'],
		z:_sprites['dirtFloor_z'],

		m_n:_sprites['dirtFloor_n_know'],
		m_e:_sprites['dirtFloor_e_know'],
		m_s:_sprites['dirtFloor_s_know'],
		m_w:_sprites['dirtFloor_w_know'],
		m_ne:_sprites['dirtFloor_ne_know'],
		m_nw:_sprites['dirtFloor_nw_know'],
		m_ns:_sprites['dirtFloor_ns_know'],
		m_ew:_sprites['dirtFloor_ew_know'],
		m_es:_sprites['dirtFloor_es_know'],
		m_ws:_sprites['dirtFloor_ws_know'],
		m_new:_sprites['dirtFloor_new_know'],
		m_nes:_sprites['dirtFloor_nes_know'],
		m_nws:_sprites['dirtFloor_nws_know'],
		m_ews:_sprites['dirtFloor_ews_know'],
		m_news:_sprites['dirtFloor_news_know'],
		m_z:_sprites['dirtFloor_z_know'],
	} );

	_TileTypes.rockFloor = new _SmartTileType( 'Rock Floor', true, true, false, _Selectors.Exclusive, {
		n:_sprites['rockFloor_n'],
		e:_sprites['rockFloor_e'],
		s:_sprites['rockFloor_s'],
		w:_sprites['rockFloor_w'],
		ne:_sprites['rockFloor_ne'],
		nw:_sprites['rockFloor_nw'],
		ns:_sprites['rockFloor_ns'],
		ew:_sprites['rockFloor_ew'],
		es:_sprites['rockFloor_es'],
		ws:_sprites['rockFloor_ws'],
		new:_sprites['rockFloor_new'],
		nes:_sprites['rockFloor_nes'],
		nws:_sprites['rockFloor_nws'],
		ews:_sprites['rockFloor_ews'],
		news:_sprites['rockFloor_news'],
		z:_sprites['rockFloor_z'],

		m_n:_sprites['rockFloor_n_know'],
		m_e:_sprites['rockFloor_e_know'],
		m_s:_sprites['rockFloor_s_know'],
		m_w:_sprites['rockFloor_w_know'],
		m_ne:_sprites['rockFloor_ne_know'],
		m_nw:_sprites['rockFloor_nw_know'],
		m_ns:_sprites['rockFloor_ns_know'],
		m_ew:_sprites['rockFloor_ew_know'],
		m_es:_sprites['rockFloor_es_know'],
		m_ws:_sprites['rockFloor_ws_know'],
		m_new:_sprites['rockFloor_new_know'],
		m_nes:_sprites['rockFloor_nes_know'],
		m_nws:_sprites['rockFloor_nws_know'],
		m_ews:_sprites['rockFloor_ews_know'],
		m_news:_sprites['rockFloor_news_know'],
		m_z:_sprites['rockFloor_z_know'],
	} );

	_TileTypes.stoneFloorSingle = new _TileType('Stone Floor', true, true, false,{
		tex:_sprites['stoneFloor_news'],
		m_tex:_sprites['m_stoneFloor_news']
	});

}
